org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false


## Environment Properties

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1


## Mod Properties

mod_id=e33chat
mod_name=E33Chat
mod_license=MIT
mod_version=2.3.15
mod_group_id=com.niuqu.chatbubble
mod_authors=E33EPUS
mod_description=Rebuilds the vanilla chat HUD in a chat-app style
